version: '2'

services:
  app_server:
    build: dev-ops/docker/containers/php7
    volumes:
      - ~/.composer/cache:/var/www/composer-cache-dir:Z
      - .:/project:Z
      - .:/var/www/shopware:Z
    links:
      - app_mysql:mysql
    environment:
      TERM: xterm
      COMPOSER_CACHE_DIR: /var/www/composer-cache-dir
    ports:
      - "8083:80"

  app_mysql:
    build: dev-ops/docker/containers/mysql
    volumes:
      - ./dev-ops/docker/_volumes/app-mysql-data:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

  app_es:
    build: dev-ops/docker/containers/elastic-search
    volumes:
      - ./dev-ops/docker/containers/elastic-search/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
      - ./dev-ops/docker/_volumes/app-es-data:/usr/share/elasticsearch/data:Z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TERM: xterm
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  app_redis:
    build: dev-ops/docker/containers/redis
    volumes:
      - ./dev-ops/docker/_volumes/app-redisdata:/data:Z
